FROM golang AS build

COPY . /work
WORKDIR /work

ARG GOOS=linux
ARG GOARCH=
ARG GOARM=
RUN env GOOS=${GOOS} GOARCH=${GOARCH} GOARM=${GOARM} CGO_ENABLED=0 go build -a -installsuffix cgo -o sdrd ./cmd/sdrd

FROM scratch

COPY --from=build /work/sdrd /start

ENTRYPOINT ["/start"]
CMD []
